FROM openjdk:17 AS build

WORKDIR /app

COPY pom.xml mvnw ./
COPY .mvn .mvn
RUN ./mvnw dependency:resolve

COPY src src
RUN ./mvnw package

FROM openjdk:17
WORKDIR /app
COPY --from=build /app/target/WorkFlow-0.0.1-SNAPSHOT.jar user-panel.jar

EXPOSE 3000

ENTRYPOINT ["java", "-jar", "user-panel.jar"]
