FROM openjdk:17 AS build

WORKDIR /app

COPY pom.xml mvnw ./
COPY .mvn .mvn
RUN chmod +x mvnw
RUN ./mvnw dependency:resolve

COPY src src
RUN ./mvnw package -DskipTests


FROM openjdk:17

WORKDIR /app

COPY --from=build /app/target/rentACar-0.0.1-SNAPSHOT.jar admin-panel.jar

EXPOSE 4000

ENTRYPOINT ["java", "-jar", "admin-panel.jar"]
