server:
  port: 8761

spring:
  application:
    name: ms-discovery

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url.defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: false
