FROM openjdk:17 AS build

WORKDIR /app

COPY pom.xml mvnw ./
COPY .mvn .mvn
RUN ./mvnw dependency:resolve

COPY src src
RUN ./mvnw package

FROM openjdk:17
WORKDIR /app
COPY --from=build /app/target/ms-discovery-0.0.1-SNAPSHOT.jar ms-discovery.jar

EXPOSE 8761

ENTRYPOINT ["java", "-jar", "ms-discovery.jar"]
